# Generated by Django 4.1.10 on 2023-09-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_logindata_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindata',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
