# Generated by Django 4.1.10 on 2023-09-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='img_uploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageFile', models.FileField(default=None, max_length=250, null=True, upload_to='uploader')),
            ],
        ),
    ]
