# Generated by Django 4.1.10 on 2023-09-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_uploader',
            name='imageFile',
            field=models.FileField(default='', upload_to='uploader/'),
            preserve_default=False,
        ),
    ]
